import {
  FaTags,
  FaCar,
  FaBuilding,
  FaBriefcase,
  FaTools,
  FaTv,
  FaMobile,
  FaLaptop,
  FaCouch,
  FaTshirt,
  FaBaby,
  FaFootballBall,
  FaWrench,
  FaHammer,
  FaGuitar,
  FaDice,
  FaDog,
  FaBook,
  FaWineBottle,
  FaShip,
  FaTractor,
  FaHandshake,
  FaCamera,
  FaHeadphones,
  FaGamepad,
  FaPalette,
  FaGem,
  FaFemale,
  FaMale,
  FaGlasses,
  FaBicycle,
  FaPlane,
  FaHome,
  FaSeedling,
  FaGraduationCap,
  FaBox,
  FaHeart,
  FaCut,
  FaUtensils,
  FaDumbbell
} from 'react-icons/fa';

export const categories = [
  { id: 1, name: 'Automotores', icon: FaCar },
  { id: 2, name: 'Inmuebles', icon: FaBuilding },
  { id: 3, name: 'Empleos', icon: FaBriefcase },
  { id: 4, name: 'Servicios', icon: FaTools },
  { id: 5, name: 'Electrodomésticos', icon: FaTv },
  { id: 6, name: 'Celulares y Telefonía', icon: FaMobile },
  { id: 7, name: 'Informática y Computación', icon: FaLaptop },
  { id: 8, name: 'Muebles y Hogar', icon: FaCouch },
  { id: 9, name: 'Indumentaria y Accesorios', icon: FaTshirt },
  { id: 10, name: 'Bebés y Niños', icon: FaBaby },
  { id: 11, name: 'Deportes y Recreación', icon: FaFootballBall },
  { id: 12, name: 'Máquinas y Equipamiento', icon: FaWrench },
  { id: 13, name: 'Ferretería y Construcción', icon: FaHammer },
  { id: 14, name: 'Instrumentos Musicales', icon: FaGuitar },
  { id: 15, name: 'Hobbies y Coleccionables', icon: FaDice },
  { id: 16, name: 'Animales y Mascotas', icon: FaDog },
  { id: 17, name: 'Librería y Artículos Escolares', icon: FaBook },
  { id: 18, name: 'Alimentos y Bebidas', icon: FaWineBottle },
  { id: 19, name: 'Náutica', icon: FaShip },
  { id: 20, name: 'Agropecuarios', icon: FaTractor },
  { id: 21, name: 'Negocios y Oportunidades', icon: FaHandshake },
  { id: 22, name: 'Fotografía y Video', icon: FaCamera },
  { id: 23, name: 'Audio y Sonido', icon: FaHeadphones },
  { id: 24, name: 'Videojuegos y Consolas', icon: FaGamepad },
  { id: 25, name: 'Arte y Artesanías', icon: FaPalette },
  { id: 26, name: 'Joyas y Relojes', icon: FaGem },
  { id: 27, name: 'Moda Mujer', icon: FaFemale },
  { id: 28, name: 'Moda Hombre', icon: FaMale },
  { id: 29, name: 'Accesorios de Moda', icon: FaGlasses },
  { id: 30, name: 'Bicicletas y Ciclismo', icon: FaBicycle },
  { id: 31, name: 'Viajes y Turismo', icon: FaPlane },
  { id: 32, name: 'Decoración del Hogar', icon: FaHome },
  { id: 33, name: 'Jardín y Aire Libre', icon: FaSeedling },
  { id: 34, name: 'Educación y Cursos', icon: FaGraduationCap },
  { id: 35, name: 'Embalajes y Logística', icon: FaBox },
  { id: 36, name: 'Salud y Belleza', icon: FaHeart },
  { id: 37, name: 'Peluquería y Estética', icon: FaCut },
  { id: 38, name: 'Restaurantes y Gastronomía', icon: FaUtensils },
  { id: 39, name: 'Gimnasios y Fitness', icon: FaDumbbell }
];

export const getIconForCategory = (categoryName) => {
  const category = categories.find(cat => 
    cat.name.toLowerCase() === categoryName.toLowerCase()
  );
  return category ? category.icon : FaTags;
};
